;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Pzt Eki 21 2019
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================


CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE 

START:
        ; Write your code here
	
	
	mov al,090h ; set 8255 control word
	mov dx, 46h  ; 8255 cw address in dx
	out dx,al ;set 8255 control register
	
ENDLESS:
	in al,40h ;read from port a
	test al , 80h; test msb of al
	jnz carp; zero flag equals to 1
	;zero flag equals to 0
	sar al ,1 ; div al by 2
	jmp output ; result is on 7-seg
	
	
	carp:
	sal al ,1 ; mul al by 2
	
	
	output:
	mov dx, 42h; address of port b
	out dx, al; write to port b
	
	
	
	
	JMP ENDLESS
CODE    ENDS
        END START