;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
DIGITS  DB 00H
SERIALDATA DB 30 DUP(?)    ; TOPSECRET'tan gelen degerler bu dizide saklanacak
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK
	START:
        MOV AX, DATA
	MOV DS, AX

	MOV DX, 070DH 
	MOV AL, 01001101B ;mod
	OUT DX, AL

	MOV AL, 40H  ;control reg ile sifirlama
	OUT DX, AL
	
	MOV AL, 01001101B ;mod
	OUT DX, AL
	
	MOV AL, 00010101B ; transmit ve receiver enable
	OUT DX, AL
	

ENDLESS:

	 MOV DX, 0709H
	 
	 ;MOV AL,59H
	  ;OUT DX,AL




   
   XOR SI,SI 
     
   
   MOV AL, 53H ;S
   OUT DX, AL
   
   CALL SLEEP
      
   MOV AL, 52H ;R
   OUT DX, AL
   
   CALL SLEEP
   

   MOV CX,5
   D5KERE:   
   
      MOV AL, 44H ;D
      OUT DX, AL
      
      CALL SLEEP
      
      	;TEKRAR:
	;IN AL, DX
	;AND AL, 02H
	;JZ TEKRAR
      
      
      IN AL,DX
      SHR AL,1 
      
      
      MOV SERIALDATA[SI],AL
      INC SI
      
      CALL SLEEP
   
   LOOP D5KERE
   
   MOV AL, 53H ;S
   OUT DX, AL
   
   CALL SLEEP
      
   MOV AL, 54H ;T
   OUT DX, AL
   
 
   CALL SLEEP
   

   
   MOV CX,5
   MOV SI,0
   WRITE:
      
      MOV AL, SERIALDATA[SI] 
      OUT DX, AL
      INC SI
      
      CALL SLEEP
      
   LOOP WRITE
   
   


        JMP ENDLESS
	
SLEEP PROC NEAR
   
   PUSH CX
   MOV CX,0FFFFH
   ATLA5: LOOP ATLA5
   MOV CX,0FFFFH
   ATLA6: LOOP ATLA6
   MOV CX,0FFFFH
   ATLA7: LOOP ATLA7
   POP CX
   
   RET
SLEEP ENDP
	
CODE    ENDS
        END START