;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
SERIALDATA  DB 15 DUP (?)
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK
START PROC FAR
        MOV AX, DATA
	MOV DS, AX
	
	MOV DX, 0314h
	MOV AL, 01001101B
	OUT DX, AL
	
	MOV AL, 40H
	OUT DX, AL
	
	MOV AL, 01001101B
	OUT DX, AL
	
	MOV AL, 00010101B
	OUT DX, AL
	

ENDLESS:

	MOV DX, 0314H

	
TEKRAR:
	IN AL, DX
	AND AL, 01H
	JZ TEKRAR
	
	MOV DX, 0310H
	MOV AL, 4CH
	OUT DX, AL
	

	MOV DX, 0314H
	
TEKRAR2:
	IN AL, DX
	AND AL, 02H
	JZ TEKRAR2
        MOV DX, 0310H
	IN AL, DX
        SHR AL,1
	mov bl,al
	mov ah,00H
	cmp al,58h
	jne devam
	MOV DX, 0314H

	
TEKRAR3:
	IN AL, DX
	AND AL, 01H
	JZ TEKRAR3
	MOV DX, 0310H
	MOV AL, bl
	OUT DX, AL
devam:

	
	
        JMP ENDLESS
	
RETF
START ENDP
	

	
CODE    ENDS
        END START