;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
MYDAT   DB 5 DUP(0)
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK

VERI_AL  PROC FAR
        PUSH BP
	
	CMP SI,4		;INDIS 5 MI ?
	JNE READ  		;INDIS 5 DEGILSE DEVAMA ATLA
	MOV SI, 0
	   
	MOV DX, 7CH		;8251 ilk adresten
		
	MOV AL, MYDAT[SI]
	OUT DX, AL
	INC SI
	
	JMP BITIS
	
READ:	
	
	MOV DX, 7CH		;8251 ilk adresten
	
	IN AL, DX
	SHR AL, 1
	INC AL 			;Okunan degeri 1 artirdi
	MOV MYDAT[SI], AL 	;Artirilan deger diziye kondu
	INC SI			;INDISI ARTTIRIYORUZ
	    
	
BITIS:

        POP BP
        IRET
VERI_AL  ENDP	

VERI_GONDER  PROC FAR
        PUSH BP
	
	CMP SI,5		;INDIS 5 MI ?
	JNE WRITE		;INDIS 5 ISE DEVAM2YE ATLA
	
	;DEVAMINDA 5 DAHA OKUMA ICIN INTERRUPT
	MOV SI,0
	MOV DX, 7CH		;8251 ilk adresten

	IN AL, DX
	SHR AL, 1
	INC AL 			;Okunan degeri 1 artirdi
	MOV MYDAT[SI], AL 	;Artirilan deger diziye kondu
	INC SI		
	
	
	
	JMP BITIS
	
WRITE:
	
	MOV DX, 7CH		;8251 ilk adresten
		
	MOV AL, MYDAT[SI]
	OUT DX, AL
	INC SI
	        
BITIS:
	
        POP BP
        IRET
VERI_GONDER  ENDP		
	
START PROC FAR
        MOV AX, DATA
	MOV DS, AX

;8251 ayarlar

	MOV DX, 7EH ;8251 baslangic adresinden itibaren yazılacak
	MOV AL, 4DH ;Mod yazmacini ayarliyoruz
	OUT DX, AL
	
	MOV AL, 40H ;Resetlemek icin
	OUT DX, AL
	
	MOV AL, 4DH ;Tekrar modu yukluyoruz
	OUT DX, AL
	
	MOV AL, 15H ;Kontrol yazmacini ayarliyoruz
	OUT DX, AL
	
;Kesme vektor tablosuna ilgili alt programlarin yazilmasi
	
	;Veri al programi icin
	XOR AX, AX
	MOV ES, AX
	MOV AL, 78H
	MOV AH, 4
	MUL AH
	MOV BX, AX
	LEA AX, VERI_AL
        MOV WORD PTR ES:[BX], AX
        MOV AX, CS
        MOV WORD PTR ES:[BX+2], AX 
	
	;Veri gonder programi icin
	XOR AX, AX
	MOV ES, AX
	MOV AL, 79H
	MOV AH, 4
	MUL AH
	MOV BX, AX
	LEA AX, VERI_GONDER
        MOV WORD PTR ES:[BX], AX
        MOV AX, CS
        MOV WORD PTR ES:[BX+2], AX 
	
	
;8259 ayarlar

	MOV AL, 13H ;ICW1 WORD
	OUT 60H, AL ;8259 baslangic adresi
	MOV AL, 78H ;ICW2 WORD
	OUT 62H, AL ;8259 son adresi
	MOV AL, 03H ;ICW4 WORD
	OUT 62H, AL ;8259 son adresi
	STI
	XOR AX, AX
	
	

	
	MOV SI, 0
	
ENDLESS:
     


JMP ENDLESS
RET
START ENDP
	
CODE    ENDS
        END START