;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
MYDAT   DB 5 DUP(0)
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK

	
VERI_AL PROC FAR

	IN AL, 7CH
	SHR AL,1
	INC AL
	MOV MYDAT[SI], AL
	INC SI
	CMP SI, 5
	JE INTRT	
	JMP BITIS
INTRT:  MOV AL,MYDAT[DI]
	INC DI
	OUT 7CH,AL
BITIS:	
	IRET 
VERI_AL ENDP


VERI_GONDER PROC FAR
	CMP SI, 5; İF(GELENELEMAN!=5) BİTİS
	JNE BITIS
	CMP DI, 5;İF(YAZILANELEMAN!=5) YAZ
	JE YAZMA
	MOV AL, MYDAT[DI]
	INC DI
	OUT 7CH, AL
	JMP BITIS
YAZMA:	
	XOR DI, DI
	XOR SI, SI    
BITIS:
	IRET
VERI_GONDER ENDP



START PROC FAR
        MOV AX, DATA
	MOV DS, AX
	
	XOR SI, SI
	XOR DI, DI
	
	;Interrupt'ların yerleştirilmesi
	XOR AX, AX
	MOV ES, AX
	MOV AL, 78H
	MOV AH, 4
	MUL AH
	MOV BX, AX
	LEA AX, VERI_AL
	MOV WORD PTR ES:[BX], AX
	MOV AX, CS
	MOV WORD PTR ES:[BX+2], AX

	LEA AX, VERI_GONDER
	MOV WORD PTR ES:[BX+4], AX
	MOV AX, CS
	MOV WORD PTR ES:[BX+6], AX
	
	;8259 un ayarlanması
	MOV AL, 01010011B
	OUT 60H, AL

	MOV AL, 01111000B
	OUT 62H, AL

	MOV AL, 00000011B
	OUT 62H, AL
	
	;8251 in ayarlanması 
	MOV AL, 01001101B
	OUT 7EH, AL
	
	MOV AL, 40H
	OUT 7EH, AL
	
	MOV AL, 01001101B
	OUT 7EH, AL
	
	MOV AL, 00010101B
	OUT 7EH, AL
	
	STI

ENDLESS:


JMP ENDLESS
RET
START ENDP
	

CODE    ENDS
        END START