;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cmt Eki 19 2019
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
DATA    SEGMENT PARA 'DATA'
DIGITS  DB  0FAH, 0F9H, 0A4H, 0F0H, 99H, 0FBH, 0FCH, 0FDH, 0H, 0FEH
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA
	
START:
        ; Write your code here
			MOV AL, 90H
			OUT 6EH, AL
			
			
ENDLESS:
	MOV AL, 0FFH ; ilk butona basýlý deðilken hiçbir þey yanmaz
	OUT 6AH, AL
	IN AL, 68H
	NOT AL           ; boþ basýlýnca ff geleceði için tersini alýyoruz
	AND AL, 0FH  ; kullanýlmayan 4 bit 0lanýr 
	XOR BH, BH
	MOV BL, AL 
	CMP AL, 00H ; 
	JNE TUSABASILDI
	JMP ENDLESS

TUSABASILDI:
	MOV SI, BX
	MOV AL, DIGITS[SI]
	OUT 6AH, AL
	IN AL, 68H
	NOT AL           ; boþ basýlýnca ff geleceði için tersini alýyoruz
	AND AL, 0FH  ; kullanýlmayan 4 bit 0lanýr

	;TEST AL, BL
	;JZ ENDLESS 

	CMP AL, 00H
	JE ENDLESS
	JMP TUSABASILDI
	

CODE    ENDS
        END START